version: "3"

services:
  nllb-translate:
    container_name: nllb-translate
    build: .
    restart: always
    ports:
      - 5001:5001
    volumes:
      - ./:/app/
    entrypoint: [
      "python3",
      "-m", "nllb_serve"
    ]
